site_name: Mailbox Mailing
repo_url: https://github.com/systopia/de.systopia.mailboxmailing
theme: material

nav:
- Home: index.md
- Introduction: Introduction.md
- Configuration: Configuration.md
- Use: Use.md
- Example and Hints: Example and Hints.md
markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
